### ISSUE TITLE
check and fix duplicate tracker ids. 

### ISSUE THREAD

**Issue by shbonita** [YsuSERESL/iTrace#37]
It might be related to a rounding issue.

**Comment by zwhile** [comment]
@meoblast001 on TobiiTracker.java lines 151 & 158 what is the significance/use of 5000 and 25000 in the while loops?

**Comment by meoblast001** [comment]
The `main` method only exists in this class for testing purposes. Those are concrete times that are used. Line 158 limits the execution time of the test to 25 seconds before it shuts down. Line 151 appears to be more or less a mock of a sleep (not really sure why I didn't use a `Thread.sleep` here...). In the first part (around line 151) the crosshair is being tested, and in the second part it simply dumps information about the point the user is looking at.

**Comment by shbonita** [comment]
@onebenclark could you let us know what you found for this one.

**Comment by onebenclark** [comment]
This was occurring because the method newGazePoint was being called multiple times for the same data. The x and y positions for these "new" gaze were different from the previous because they are being averaged. To fix this we ignored the new gazes if they are within one ms of the previous gaze.
