### ISSUE TITLE
Capture eye gaze on opening and closing brace 

### ISSUE THREAD

**Issue by shbonita** [YsuSERESL/iTrace#4]
The data files should specify if the eye gaze landed on { or }.  Since this is only 1 character in length a bounding box or smoothing function on eye gaze data may need to be applied.

**Comment by onebenclark** [comment]
This could be handled by checking the length of the gaze's line's content when nothing is registered. If the line is one or two chars long check and the x position is within a certain range from the content on the x -axis register the gaze as looking at the content.
