### ISSUE TITLE
Change time format in data.

### ISSUE THREAD

**Issue by onebenclark** [YsuSERESL/iTrace#50]
Change the time attributes in the data from tracker time, system time and nano time to a yyyy-mm-dd hh-mm-ss.mmm timestamp and milliseconds relative to the start of the session.

**Comment by onebenclark** [comment]
I believe this is ready to be merged minus one issue. I was using nanoTime set the nanoseconds in the timestamp but this is incorrect because System.nanoTime() is meant for judging elapsed time, like session_time, but is not relative to a specific time like System.currentTimeMillis(). Since we are operating in 16ms timeframe with the x60 can we leave the timestamp with ms precision even though Andy Begel's timestamp is more precise?

**Comment by shbonita** [comment]
Milliseconds should be fine for now.

**Comment by shbonita** [comment]
@onebenclark is this issue complete?

**Comment by onebenclark** [comment]
There are two new time attributes.
A timestamp with the form YYYY-MM-DDTHH:mm:SS.sss-00:00.
The session time is the time in nanoseconds since the Start Tracking button is pressed.
The older time attributes will be left in until removing them won't break something else.
This branch has been merged with master.
