### ISSUE TITLE
Display some identification of gaze events in status bar

### ISSUE THREAD

**Issue by shbonita** [YsuSERESL/iTrace#51]
Display some identification such as time in the status bar.  This will help with syncing with screen recordings.

**Comment by shbonita** [comment]
@onebenclark could you let us know how this is implemented?

**Comment by onebenclark** [comment]
Messages can be sent to the status bar through IActionBars and IStatusLineManager. ViewParts have a method to get the actionBars which have the statusLineManager. Only the active view has access to the status bar.
The session time of a gaze is written to the status bar when the gaze is added to the queue. The message is sent through the ControlView and the open editorPart. However if another view is the active one we lose control. Issue 56 was opened to address this.
This was implemented in the branch for issue 50 and has been merged.
