### ISSUE TITLE
highlight token when display cursor is on

### ISSUE THREAD

**Issue by shbonita** [YsuSERESL/iTrace#58]
When the display cursor is on, highlight the token that is being looked at.  This can be done by placing a bounding box over the token. We can use the last 10 gazes to determine the token being looked at.

**Comment by onebenclark** [comment]
@shbonita I will take this if you want me to.

**Comment by shbonita** [comment]
@onebenclark yes thanks. This is high priority.

**Comment by shbonita** [comment]
We should plot the eye gaze as little circles on the text and highlight the token when N gazes fall within the token area. N can be experimented with. We could start with 10.

**Comment by onebenclark** [comment]
This issue is finished and merged
