### ISSUE TITLE
refactor gaze distribution

### ISSUE THREAD

**Issue by shbonita** [YsuSERESL/iTrace#59]

**Comment by onebenclark** [comment]
Currently the GazeTransport provides a queue of gazes for each thread that needs gaze data. There have three instances where adding a new thread accessing the gazetransport has made itrace run sluggish and new feature wouldn't work. We should see if an event broker layout using the IEventBroker interfface would work better for us.

**Comment by onebenclark** [comment]
Gray out start tracking button while tracking is in progress.

**Comment by onebenclark** [comment]
This issue's branch has been merged.
