### ISSUE TITLE
improve display calibration status window after calibration

### ISSUE THREAD

**Issue by shbonita** [YsuSERESL/iTrace#60]
we need to know which of the nine points are good.

**Comment by onebenclark** [comment]
![newstatusscreen](https://cloud.githubusercontent.com/assets/15931124/19533648/a881c11e-960e-11e6-9b7d-aba29de87c77.png)

**Comment by onebenclark** [comment]
Ignore the bad calibration.

**Comment by onebenclark** [comment]
Added animated calibration. However with the eyex the calibration fails because of saying that there is not enough data, and with the x60 the stopcalibration call fails. I will keep working on it.
@jennalwise If you have any suggestions let me know.

**Comment by shbonita** [comment]
@onebenclark did you check the tobii dev manual to see what they recommend.  There is a para or two listed I believe.

**Comment by onebenclark** [comment]
@shbonita I have checked it and I'm following it as close as I can.

**Comment by onebenclark** [comment]
We have figured it out. The use calibration point call expects ADSC points, where x and y are a value between 0.0 and 1.0. Long story short wasn't passing those when I thought I was.

**Comment by onebenclark** [comment]
Waiting on Pull request.
