### ISSUE TITLE
Token Highlighter NullPointerException

### ISSUE THREAD

**Issue by jennalwise** [YsuSERESL/iTrace#69]
When opening a browser editor this happens:

```
java.lang.NullPointerException
    at edu.ysu.itrace.TokenHighlighter.<init>(TokenHighlighter.java:186)
    at edu.ysu.itrace.Activator.setActiveEditor(Activator.java:73)
    at edu.ysu.itrace.ControlView.partActivated(ControlView.java:565)

```

(not full stack trace)
These are the lines where the exception is thrown (problem line is starred):

```
public TokenHighlighter(IEditorPart editorPart, boolean show){      
        this.editorPart = editorPart;
        this.styledText = (StyledText) this.editorPart.getAdapter(Control.class);
        ITextOperationTarget t = (ITextOperationTarget) editorPart.getAdapter(ITextOperationTarget.class);
        if(t instanceof ProjectionViewer) projectionViewer = (ProjectionViewer) t;
        **this.styledText.addPaintListener(this);**
        this.gazeHandler = new StyledTextGazeHandler(styledText);
        this.show = show;
        this.numberOfPoints = 10;
        this.points = new Point[numberOfPoints];
        this.pointIndex = 0;
        this.nulls = 0;
```

It seems as though the TokenHighlighter is assuming that all editorParts supplied to it are styledTexts. The line: this.styledText = (StyledText) this.editorPart.getAdapter(Control.class); would set styledText to null if the EditorPart is associated with a browser. A simple check for null should fix it assuming that no other portions of the TokenHighlighter needs changed to account for this and that it is true that we aren't checking that the editorPart is associated with a browser vs. a styledText.

I would change it myself, except for I am not sure if other parts of the TokenHighlighter need changed and it would take me much longer than @onebenclark to fix.

**Comment by onebenclark** [comment]
A simple check should be sufficient. But it should be outside of the constructor so we are not creating TokenHighlighters for the wrong things. I don't think there need to be any changes inside the highlighter, just changes where we create them. I'll take a look tomorrow evening.

**Comment by onebenclark** [comment]
It may be best to remove the editorPart member if it is not used other than to get the styledText. We could pass in the styledText to the constructor instead of the whole editorPart. I don't remember if it is needed of the top of my head.

**Comment by onebenclark** [comment]
Yes I think we could remove the editorPart.

**Comment by onebenclark** [comment]
@jennalwise Alright the branch issue69-HighlighterBrowserException has the fix implemented. I tested it and haven't gotten the exception you described, but if you could test it I'd appreciate it since you can better recreate the circumstances that caused it. Let me know, then I'll merge this with master.

**Comment by jennalwise** [comment]
Okay thanks, I will test it tonight.

**Comment by jennalwise** [comment]
No longer getting the error when opening a browser, however I am getting another NullPointerException when closing all EditorParts. It will not throw an exception with just a browser editor open or just a styledtext editor open, but it will when I close them all out. Also, on the next launch of the application the iTrace controller will not open due to this problem. You have to open an editor and then close the launched Eclipse IDE and then reopen it for iTrace to work. Here is the first error I get when closing all of the editors, while running iTrace:
`java.lang.NullPointerException
	at edu.ysu.itrace.Activator.setActiveEditor(Activator.java:76)`

**Comment by onebenclark** [comment]
I pushed up a fix to those exceptions. If there is anything else let me know.

**Comment by onebenclark** [comment]
@jennalwise If you're okay with I will go ahead merge this into master.

**Comment by jennalwise** [comment]
@onebenclark I haven't been able to test it. I won't get to it until tonight. If you feel that you've tested it enough and you aren't getting anymore NPEs then go ahead and merge it.

**Comment by onebenclark** [comment]
The fix for this bug has been merged into master.
