### ISSUE TITLE
Test iTrace with TX300

### ISSUE THREAD

**Issue by onebenclark** [YsuSERESL/iTrace#72]
The tx300 needs to be tested with iTrace. To do this we need to set up one of the new computers with iTrace to work with the tobii tracker.

**Comment by shbonita** [comment]
@onebenclark @jennalwise take a look at how to get this working on the new computers in 315. The TX-300 and the X3-120 both need iTrace running and stable.

**Comment by onebenclark** [comment]
iTrace is working with the TX300

**Comment by shbonita** [comment]
@onebenclark could you give us a short description of what was needed to be done to make this work?

**Comment by onebenclark** [comment]
https://github.com/YsuSERESL/iTrace/blob/master/jni/TobiiTracker/TOBIITRACKER.README.md

**Comment by shbonita** [comment]
see commit 5db1eab for what was changed.

**Comment by shbonita** [comment]
I believe this issue can safely be closed.

**Comment by onebenclark** [comment]
Works for me.
